#!/bin/bash
set -e
trap cleanup INT
cleanup() {
    if [ -n "$cluster_id" ]; then 
        echo "Terminating ... cluster ID: ${cluster_id}"; 
        aws2 emr terminate-clusters --cluster-ids "$cluster_id"
        sleep 5
    fi
    exit
}

update_script_bucket(){
    n=0
    retrytime=3
    until aws2 s3api head-bucket --bucket "$s3_bucket_scripts" 2>/dev/null; do
        if [ $n -ge $retrytime ]; then
            break
        fi
        ((++n))
        echo "Bucket not up, retrying ..."
        sleep 20
    done

    if [ $n -le $retrytime ]; then
        aws2 s3api put-bucket-versioning --bucket "${s3_bucket_scripts}" --versioning-configuration Status=Enabled
        aws2 s3 sync "s3://dsc102-pa2" "s3://${s3_bucket_scripts_folder}"
    else
        echo "Bucket not up, retry timeout"
        exit 1
    fi
}

cluster_id=''
spot='false'
region='us-west-2'
label='emr-5.28.0'
num_worker=4
deploy='false'
theia='false'
bootstrap_path='s3://dsc102-pa2-public/bootstrap-scripts/setup-common.sh'


while getopts 'u:bf:vr:l:k:n:d:p:t' flag; do
  case "${flag}" in
    u) pid="${OPTARG}" ;;
    b) spot='true' ;;
    r) region="${OPTARG}" ;;
    l) label="${OPTARG}" ;;
    k) key="${OPTARG}" ;;
    n) num_worker=${OPTARG} ;;
    d) deploy='true' ;;
    p) bootstrap_path="${OPTARG}" ;;
    t) theia='true' ;;
    ?) printf '\nUsage: %s: [-u:] your pid [-b] if set, use spot [-r:] region [-l:] EMR label
     [-k:] key name [-n:] number of workers [-d] if set, use deployment env
     [-p:] bootstrap script path 
     [-t] if set, setup theia IDE on master node port 3000\n' $0; exit 2 ;;
  esac
done
export AWS_DEFAULT_REGION="${region}"



declare -a arr_name=('-p' '-k')
declare -a arr=("$pid" "$key")

for ((i=0;i<${#arr[@]};++i)); do
    if [ -z "${arr[i]}" ]; then
        echo "Error: argument ${arr_name} is required."
        exit 1
    fi
done


s3_bucket_logs=${pid}-emr-logs
s3_bucket_scripts=${pid}-pa2
s3_bucket_scripts_folder=${s3_bucket_scripts}/src
emr_cluster=${pid}-emr-cluster
if [[ -n "$pid" ]]; then
    if aws2 s3api head-bucket --bucket "$s3_bucket_logs" 2>/dev/null; then
        echo "emr logs bucket already exists, skipping"
    else
        echo "creating emr logs bucket"
        aws2 s3api create-bucket --acl private --bucket "${s3_bucket_logs}" --region "${region}" --create-bucket-configuration LocationConstraint="${region}"
    fi
    if aws2 s3api head-bucket --bucket "$s3_bucket_scripts" 2>/dev/null; then
        echo "emr scripts bucket already exists, updating the bucket with missing files"
        update_script_bucket
    else
        echo "creating emr scripts bucket"
        aws2 s3api create-bucket --acl private --bucket "${s3_bucket_scripts}" --region "${region}" --create-bucket-configuration LocationConstraint="${region}" &&
        echo "copying pa2 scripts ..."
        update_script_bucket

    fi
else
    echo "argument error: pid"
    exit 1
fi

if [ "$deploy" = 'true' ]; then

    instance_type="m5.xlarge"
else
    instance_type="m4.large"
    spot='true'    
fi

if [ "$spot" = 'true' ]; then
    instance_group_core="InstanceCount=$num_worker,InstanceType=$instance_type,BidPrice=OnDemandPrice"
else
    instance_group_core="InstanceCount=$num_worker,InstanceType=$instance_type"    
fi

ret=$(aws2 emr create-cluster \
--release-label "${label}" \
--instance-groups InstanceGroupType=MASTER,InstanceCount=1,InstanceType=$instance_type InstanceGroupType=CORE,"$instance_group_core" \
--use-default-roles \
--ec2-attributes KeyName="${key}"  \
--applications Name=Spark Name=Hadoop \
--name="$emr_cluster" \
--log-uri s3://"${s3_bucket_logs}" \
--bootstrap-actions Path="$bootstrap_path",Args=["${pid}","s3://${s3_bucket_scripts_folder}","${region}","${theia}"] \
--configurations '[{"Classification":"spark","Properties":{"maximizeResourceAllocation":"true","spark.dynamicAllocation.enabled":"false"}}]'
) &&
cluster_id=$(echo $ret | jq -r '.ClusterId')

if [  -z "$cluster_id" ]; then
    echo "cluster failed to start"
    exit
fi
# 
echo "Cluster starting ... cluster ID: ${cluster_id}"


sleep 20
state=''
until [ "$state" = "WAITING" ]; do
    state=$(aws2 emr describe-cluster --cluster-id "${cluster_id}" | jq -r .Cluster.Status.State)
    echo "Current cluster state: ${state}"
    if [[ ("${state}" = "TERMINATED") || ("${state}" = "TERMINATING") || ("${state}" = "TERMINATED_WITH_ERRORS") ]]; then
        echo "Cluster terminated accidently. Check logs on AWS console."
        break
    fi
    sleep 20
done

if [ "$state" = "WAITING" ]; then
    echo "Cluster is up"
fi

ret=$(aws2 emr describe-cluster --cluster-id "${cluster_id}")
dns_name=$(echo $ret | jq -r '.Cluster.MasterPublicDnsName')
echo "Cluster specs: region: ${region}, instance type: ${instance_type}, worker number: ${num_worker}, spot option: ${spot}"
echo "Master public DNS name: ${dns_name}, user name: hadoop"

# --steps Type=CUSTOM_JAR,Name=CustomJAR,ActionOnFailure=CONTINUE,Jar=s3://"${region}".elasticmapreduce/libs/script-runner/script-runner.jar,Args=["s3://YOUR_BUCKET/YOUR_SHELL_SCRIPT.sh"]
